### ISSUE TITLE
Framework Fails to Build

### ISSUE THREAD

**Issue by mdznr** [spotify/SPTPersistentCache#112]
When embedding the SPTPersistentCacheFramework Xcode project in your Xcode project as a dependency, the project fails to build in file SPTPersistentCache.h

'SPTPersistentCache/SPTPersistentCacheImplementation.h' file not found

It doesn't seem like this file was added to SPTPersistentCacheFramework.xcodeproj

**Comment by damiankolasinski** [comment]
I have created PR that is fixing it https://github.com/spotify/SPTPersistentCache/pull/119
