### ISSUE TITLE
"Messaging unqualified id" error in Xcode 11b1

### ISSUE THREAD

**Issue by erikkerber** [spotify/SPTPersistentCache#114]
Buildng the app with Xcode 11b1 results in 3 of the following errors:

```
Messaging unqualified id
```

in:

SPTPersistentCacheOptions.mL111
SPTPersistentCache.mL967
SPTPersistentCache.mL986

I admit I am a bit miffed on what the _actual_ problem is. Despite a few years of exclusive Swift development, I feel like I should be able to infer what it doesn't like about the object being messaged in these 3 cases. 

In the first, `init` is triggering the warning.
In the second two, `integerValue`.

**Comment by mdznr** [comment]
Any updates on getting this to build on Xcode 11?

**Comment by erikkerber** [comment]
I've filed a radar/feedback to Apple.

My visit to the labs confirmed this is unexpected behavior. I'm not sure on a workaround.

**Comment by erikkerber** [comment]
Reply I got:

> The diagnostic is only enabled if you use -Weverything, or -Wobjc-messaging-id. It looks like it isn’t being disable correctly:
> ``` 
> SPTPersistentCache/ci/spotify_os.xcconfig:WARNING_CFLAGS = -Weverything ….
> SPTPersistentCache/ci/spotify_os.xcconfig:WARNING_CFLAGS_XCODE_1000 = -Wno-objc-messaging-id
> ```
>You have to properly disable it, without qualifying it for the specific Xcode version.

Which is a weird reply because it doesn't really help solve what the _problem_ is, just how to disable the warning.

**Comment by erikkerber** [comment]
@dflems Is this on your radar by any chance? It can be solved by removing that level of warning, but I'm not sure if there's a fix to the code itself that will omit the warning.

SPTPersistentCache will not build using the GM of Xcode that is likely to be released next week otherwise.

**Comment by dflems** [comment]
@eskerber this has been fixed as of #116
