### ISSUE TITLE
currentTimeCallback, do we need it?

### ISSUE THREAD

**Issue by ChocoChipset** [spotify/SPTPersistentCache#20]
Just wondering if we really need the `currentTimeCallback` parameter in `SPTPersistentCacheOptions`. 

It makes the API more complex and I'm not sure if it's a common to require something different than the default implementation we provide.

@spotify/objc-dev

**Comment by 8W9aG** [comment]
I do not think we need it :+1:

**Comment by rastersize** [comment]
I agree.

In general we should try to simplify the API. For example by reducing the number of methods on `SPTPersistentCache`. There are lots of very similar methods that make it difficult to know which to use.

**Comment by dflems** [comment]
I originally thought we used that for testing purposes. Looks like we don't use it at all. Looks ok to remove :+1:

**Comment by ChocoChipset** [comment]
Fixed and merged.
