### ISSUE TITLE
Static or dynamic lib doesnt work properly.

### ISSUE THREAD

**Issue by serhatsezer** [spotify/SPTPersistentCache#73]
I added this framework going to select add files and import to xcproj file but icannot import any file. Have you ever tested for new projects?

**Comment by 8W9aG** [comment]
How have you added this project to your project? You can see via the demo project in the workspace how to properly import this project and use it in your app (as a static library).

**Comment by serhatsezer** [comment]
@8W9aG  Thank you for your reply. Yes. it is the first thing i do when i want to decide to use any framework. But demo code and how to use document code are different. It works well with demo but doesnt work my project.

**Comment by 8W9aG** [comment]
What is your error exactly? And how are you importing this framework into your project?
