### ISSUE TITLE
Framework is missing CFBundleVersion value

### ISSUE THREAD

**Issue by atticus** [spotify/SPTPersistentCache#76]
The pre-built framework under Releases is missing the CFBundleVersion value in Info.plist. This means that apps containing the framework can't be submitted to the App Store. I just modified it locally to be '1.0.0'.

More info on the App Store error when uploading an app with this framework:
https://forums.developer.apple.com/thread/23778

**Comment by 8W9aG** [comment]
👍 Thanks for this report, I will solve this in 1.1.0 (coming very soon)

**Comment by 8W9aG** [comment]
Should be solved in the latest release
