### ISSUE TITLE
Need a new version?

### ISSUE THREAD

**Issue by migrant** [spotify/SPTPersistentCache#82]
There are a lot of commits after releasing 1.0. So should this project release a new version up to date ?

**Comment by 8W9aG** [comment]
Yes, I will look at doing this either tomorrow or next Friday depending on the stability of the latest version in the wild on the Spotify client

**Comment by migrant** [comment]
Thank you for replying. Looking forward to the new version.

**Comment by 8W9aG** [comment]
New version out
