### ISSUE TITLE
Wrong nullability flags on SPTPersistentCacheResponse

### ISSUE THREAD

**Issue by dral3x** [spotify/SPTPersistentCache#86]
The interface of `SPTPersistentCacheResponse` tells the compiler that all its properties are NONNULL but it's obvious that it's not true, you cannot have `result` and `error` instantiated at the same time.

This is a big issue in Swift3 projects, because if you check directly the presence of `record` without checking `result` before, the app will crash at runtime, because the compiler cannot let you use optional access to these properties.

A corrected version of it could be
```
@interface SPTPersistentCacheResponse : NSObject

/**
 * @see SPTPersistentCacheResponseCode
 */
@property (nonatomic, assign, readonly) SPTPersistentCacheResponseCode result;
/**
 * Defines error of response if appliable
 */
@property (nonatomic, strong, readonly, nullable) NSError *error;
/**
 * @see SPTPersistentCacheRecord
 */
@property (nonatomic, strong, readonly, nullable) SPTPersistentCacheRecord *record;

@end
```

**Comment by rastersize** [comment]
Thanks for the report @dral3x, I’m assembling a PR to fix the issue.

**Comment by rastersize** [comment]
@dral3x https://github.com/spotify/SPTPersistentCache/pull/87 should fix the issue.

**Comment by dral3x** [comment]
Looking at the PR I agree with you.

Super fast fix @rastersize 👍

**Comment by rastersize** [comment]
Closing as the PR has been merged.
